DROP TABLE IF EXISTS user;
CREATE TABLE user (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
email TEXT NOT NULL UNIQUE,
password TEXT NOT NULL
);

DROP TABLE IF EXISTS day;
CREATE TABLE day (
id INTEGER PRIMARY KEY,
user_id INTEGER NOT NULL,
date date NOT NULL,
total INTEGER NOT NULL,
completed INTEGER NOT NULL,
social INTEGER NOT NULL,
health INTEGER NOT NULL,
overall INTEGER NOT NULL,
note TEXT,
FOREIGN KEY (user_id) REFERENCES user(id)
);

DROP TABLE IF EXISTS report;
CREATE TABLE report(
id INTEGER PRIMARY KEY,
user_id INTEGER NOT NULL,
month INTEGER NOT NULL,
hasSent INTEGER NOT NULL, /* 1 true */
year INTEGER NOT NULL,
email TEXT NOT NULL,
FOREIGN KEY (email) REFERENCES user(email),
FOREIGN KEY (user_id) REFERENCES user(id)
);

DROP TABLE IF EXISTS rating_scales;
CREATE TABLE rating_scales(
id INTEGER PRIMARY KEY,
text TEXT NOT NULL,
value TEXT NOT NULL
);